services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudproject-backend-container
    ports:
     - "3000:3000"
    env_file:
     - .env 
    volumes:
     - ./src:/app/src 
    depends_on:
      redis : 
        condition : service_healthy
    networks:
      - project-network
    restart : unless-stopped  

  redis:
      image: redis:7-alpine
      container_name : redis-container
      ports : 
        - "6379:6379"
      command : >
        redis-server
        --requirepass redisCache_Password
        --maxmemory 512mb
        --maxmemory-policy allkeys-lru
        --appendonly yes
      volumes:
        - redis_data:/data            
      networks:
        - project-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "localpassword", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  redis_data:

networks:
  project-network :
    driver : bridge
        

